# Generated by Django 3.2.25 on 2025-01-19 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20250116_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('active', 'Активно'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус'),
        ),
    ]
